In [2]:
import requests
import csv
import json

In [5]:
api_key = 'qyjOJtbJtxhIhmx4YsPfSszYb2fzPKxW'
url = "https://app.ticketmaster.com/discovery/v2/events"  # API endpoint

In [11]:
import requests
import pandas as pd

# API URL
api_url = "https://api.covid19tracker.ca/reports"

# Make a request to the API
response = requests.get(api_url)

if response.status_code == 200:
    # Convert JSON data to a DataFrame
    data = response.json()
    df = pd.json_normalize(data, 'data')
    
    # Save the DataFrame to a CSV file
    df.to_csv('covid19_data.csv', index=False)
else:
    print("Failed to fetch data from the API")

In [12]:
df

,date,change_cases,change_fatalities,change_tests,change_hospitalizations,change_criticals,change_recoveries,change_vaccinations,change_vaccinated,change_boosters_1,...,total_fatalities,total_tests,total_hospitalizations,total_criticals,total_recoveries,total_vaccinations,total_vaccinated,total_boosters_1,total_boosters_2,total_vaccines_distributed
0,2020-01-25,1,0,2,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
1,2020-01-26,1,0,4,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0
2,2020-01-27,0,0,20,0,0,0,0,0,0,...,0,26,0,0,0,0,0,0,0,0
3,2020-01-28,1,0,10,0,0,0,0,0,0,...,0,36,0,0,0,0,0,0,0,0
4,2020-01-29,0,0,3,0,0,0,0,0,0,...,0,39,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400,2023-11-30,-3,0,0,9,-2,0,0,0,0,...,32505,30683931,2586,82,2060109,52164282,16256947,10184967,5745224,52613016
1401,2023-12-01,1,0,0,-9,-5,0,0,0,0,...,19001,16733572,1728,45,1099129,24741756,7245287,4750427,2696862,23092789
1402,2023-12-04,4991,0,0,18,1,0,0,0,0,...,19001,16733572,1746,46,1099129,24741756,7245287,4750427,2696862,23092789
1403,2023-12-05,-4,0,0,33,-6,0,0,0,0,...,19001,16733572,1779,40,1099129,24741756,7245287,4750427,2696862,23092789
1404,2023-12-06,19,83,0,425,0,0,113723,669,2803,...,24902,23647154,2446,47,1622808,34932877,10694888,6584634,3867348,35371888

In [13]:
import requests
import pandas as pd

# API URL
api_url = "https://api.covid19tracker.ca/summary/split"

# Make a request to the API
response = requests.get(api_url)

if response.status_code == 200:
    # Convert JSON data to a DataFrame
    data = response.json()
    df2 = pd.json_normalize(data, 'data')
    
    # Save the DataFrame to a CSV file
    df2.to_csv('summary.csv', index=False)
else:
    print("Failed to fetch data from the API")

In [4]:
import requests
import pandas as pd

# API URL
api_url = "https://api.covid19tracker.ca/summary/split"

# Make a request to the API
response = requests.get(api_url)
if response.status_code == 200:
    # Convert JSON data to a DataFrame
    data = response.json()
    df2 = pd.json_normalize(data)
    print(df2.last_updated)

0    2023-12-16 02:45:09
Name: last_updated, dtype: object

In [14]:
df2

,province,date,change_cases,change_fatalities,change_tests,change_hospitalizations,change_criticals,change_recoveries,change_vaccinations,change_vaccinated,...,total_fatalities,total_tests,total_hospitalizations,total_criticals,total_recoveries,total_vaccinations,total_vaccinated,total_boosters_1,total_boosters_2,total_vaccines_distributed
0,ON,2023-11-29,0,0,0,0,0,0,27454,181,...,16404,26834981,812,80,1587996,40634760,12189874,7703657,8077627,38554461
1,QC,2023-12-06,19,83,0,425,0,0,113723,669,...,19084,16733572,2204,40,1099129,24855479,7245956,4753230,2708111,23092789
2,NS,2022-11-17,0,0,0,0,0,0,0,0,...,451,1777959,44,8,43018,2235685,842600,503257,0,2518832
3,NB,2022-11-17,0,0,0,0,0,0,0,0,...,438,782596,22,1,65138,1757172,661271,395689,0,2212445
4,MB,2023-11-30,0,0,0,0,0,0,0,0,...,2256,1556623,291,5,129338,3001252,1101542,607635,146806,3842358
5,BC,2023-11-30,0,0,0,0,0,0,0,0,...,5430,5480154,316,20,307963,14343876,4461186,2995501,1742319,13398770
6,PE,2022-11-17,0,0,0,0,0,0,0,0,...,46,255441,10,1,41242,391227,144466,83158,7449,448875
7,SK,2022-11-17,0,0,0,0,0,0,0,0,...,1480,1564562,147,5,113023,2630158,920507,516000,208425,3155335
8,AB,2023-12-06,0,0,0,0,0,0,0,0,...,5818,6913582,242,7,523679,10077398,3448932,1831404,1159237,12279099
9,NL,2022-11-17,0,0,0,0,0,0,0,0,...,198,528651,3,0,25162,1264499,476756,289311,0,1744454
10,NT,2022-11-17,0,0,0,0,0,0,0,0,...,22,40201,0,0,11327,102863,39663,20278,1828,118910
11,YT,2022-11-17,0,0,0,0,0,0,0,0,...,26,30343,0,0,4489,92743,35380,20672,0,107460
12,NU,2022-11-17,0,0,0,0,0,0,0,0,...,7,38861,0,0,3435,77083,29021,14519,0,112230

In [16]:
import requests
import pandas as pd

# API URL
api_url = "https://api.covid19tracker.ca/provinces"

# Make a request to the API
response = requests.get(api_url)

if response.status_code == 200:
    # Convert JSON data to a DataFrame
    data = response.json()
    df3 = pd.json_normalize(data)
    
    # Save the DataFrame to a CSV file
    df3.to_csv('provinces.csv', index=False)
else:
    print("Failed to fetch data from the API")

In [17]:
df3

,id,code,name,data_source,population,area,gdp,geographic,data_status,created_at,updated_at,density
0,1,ON,Ontario,None,14826276.0,917741.0,857384.0,1,Reported,None,2023-12-01T04:58:28.000000Z,16.155185
1,2,QC,Quebec,None,8604495.0,1356128.0,439375.0,1,Reported,None,2023-12-07T04:04:23.000000Z,6.344899
2,3,NS,Nova Scotia,None,992055.0,53338.0,44354.0,1,No report expected today,None,2022-08-15T22:52:42.000000Z,18.599404
3,4,NB,New Brunswick,None,789225.0,71450.0,36966.0,1,Reported,None,2022-08-15T22:50:10.000000Z,11.045836
4,5,MB,Manitoba,None,1383765.0,553556.0,72688.0,1,No report expected today,None,2023-12-01T05:02:40.000000Z,2.499774
5,6,BC,British Columbia,None,5214805.0,925186.0,295401.0,1,Reported,None,2023-12-01T05:19:44.000000Z,5.636494
6,7,PE,Prince Edward Island,None,164318.0,5660.0,6994.0,1,Reported,None,2022-08-15T22:50:27.000000Z,29.031449
7,8,SK,Saskatchewan,None,1179844.0,591670.0,80679.0,1,No report expected today,None,2022-10-21T16:51:04.000000Z,1.994091
8,9,AB,Alberta,None,4442879.0,642317.0,344812.0,1,Reported,None,2023-12-07T04:07:07.000000Z,6.916957
9,10,NL,Newfoundland and Labrador,None,520553.0,373872.0,33241.0,1,No report expected today,None,2022-08-15T22:50:18.000000Z,1.392329
10,11,NT,Northwest Territories,None,45504.0,1183085.0,4730.0,1,No report expected today,None,2022-08-15T22:50:34.000000Z,0.038462
11,12,YT,Yukon,None,42986.0,474391.0,3046.0,1,Reported,None,2022-08-15T22:51:21.000000Z,0.090613
12,13,NU,Nunavut,None,39403.0,1936113.0,3421.0,1,No report expected today,None,2022-08-15T22:51:02.000000Z,0.020352
13,14,_RC,Repatriated Canadians,None,NaN,NaN,NaN,0,,None,None,NaN
14,15,FA,Federal Allocation,None,NaN,NaN,NaN,0,,None,2022-03-10T20:41:40.000000Z,NaN
15,16,NFR,National Federal Reserve,None,NaN,NaN,NaN,0,,None,2022-08-15T22:51:36.000000Z,NaN

In [2]:
import requests
import pandas as pd

# API URL
api_url = "https://api.covid19tracker.ca/reports/province/on"

# Make a request to the API
response = requests.get(api_url)

if response.status_code == 200:
    # Convert JSON data to a DataFrame
    data = response.json()
    df4 = pd.json_normalize(data, 'data')
    
    # Save the DataFrame to a CSV file
    df4.to_csv('report_ontario.csv', index=False)
else:
    print("Failed to fetch data from the API")

In [3]:
df4

,date,change_cases,change_fatalities,change_tests,change_hospitalizations,change_criticals,change_recoveries,change_vaccinations,change_vaccinated,change_boosters_1,...,total_fatalities,total_tests,total_hospitalizations,total_criticals,total_recoveries,total_vaccinations,total_vaccinated,total_boosters_1,total_boosters_2,total_vaccines_distributed
0,2020-01-25,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-01-26,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020-01-27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-01-28,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-01-29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,2023-12-02,0,0,0,0,0,0,25016,189,861,...,16404,26834981,812,80,1587996,40725280,12189442,7705469,8166406,38554461
1395,2023-12-03,0,0,0,0,0,0,13333,168,727,...,16404,26834981,812,80,1587996,40738613,12189610,7706196,8178508,38554461
1396,2023-12-04,0,0,0,0,0,0,5943,55,288,...,16404,26834981,812,80,1587996,40744556,12189665,7706484,8183971,38554461
1397,2023-12-05,0,0,0,0,0,0,19543,126,625,...,16404,26834981,812,80,1587996,40764099,12189791,7707109,8202478,38554461
1398,2023-12-06,0,0,0,0,0,0,23579,161,723,...,16404,26834981,812,80,1587996,40787678,12189952,7707832,8224793,38554461

In [1]:
import requests
import pandas as pd

# API URL
api_url = "https://api.covid19tracker.ca/reports/province/qc"

# Make a request to the API
response = requests.get(api_url)

if response.status_code == 200:
    # Convert JSON data to a DataFrame
    data = response.json()
    df5 = pd.json_normalize(data, 'data')
    
    # Save the DataFrame to a CSV file
    df5.to_csv('report_quebeck.csv', index=False)
else:
    print("Failed to fetch data from the API")

In [2]:
df5

,date,change_cases,change_fatalities,change_tests,change_hospitalizations,change_criticals,change_recoveries,change_vaccinations,change_vaccinated,change_boosters_1,...,total_fatalities,total_tests,total_hospitalizations,total_criticals,total_recoveries,total_vaccinations,total_vaccinated,total_boosters_1,total_boosters_2,total_vaccines_distributed
0,2020-01-25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-01-26,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020-01-27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-01-28,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-01-29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,2023-12-04,4991,0,0,18,1,0,0,0,0,...,19001,16733572,1746,46,1099129,24741756,7245287,4750427,2696862,23092789
1296,2023-12-05,-4,0,0,33,-6,0,0,0,0,...,19001,16733572,1779,40,1099129,24741756,7245287,4750427,2696862,23092789
1297,2023-12-06,19,83,0,425,0,0,113723,669,2803,...,19084,16733572,2204,40,1099129,24855479,7245956,4753230,2708111,23092789
1298,2023-12-07,58,0,0,0,0,0,0,0,0,...,19084,16733572,2204,40,1099129,24855479,7245956,4753230,2708111,23092789
1299,2023-12-08,0,0,0,-26,0,0,0,0,0,...,19084,16733572,2178,40,1099129,24855479,7245956,4753230,2708111,23092789